services:
  # --- 1) Сервис с базой PostgreSQL ---
  library-db:
    image: postgres:latest
    container_name: library-db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      # Пробрасываем порт 5432 на хост, чтобы к базе можно было обратиться извне,
      # но внутри сети контейнеры всё равно будут «видеть» друг друга по внутреннему имени.
      - "5432:5432"
    networks:
      - library-network

  # --- 2) Сервис с интерфейсом pgAdmin4 ---
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: redangry73@mail.ru
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      # Пробрасываем веб-интерфейс pgAdmin на 8080 хоста → 80 внутри контейнера
      - "8080:80"
    depends_on:
      - library-db
    networks:
      - library-network

# --- 3) Пользовательская сеть, в которой оба контейнера «видят» друг друга ---
networks:
  library-network:
    driver: bridge
